name: Guaranteed Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build APK
      run: |
        ./gradlew clean
        ./gradlew assembleDebug --no-daemon --stacktrace
    
    - name: List build outputs
      run: |
        echo "=== Build outputs ==="
        find app/build -name "*.apk" -type f || echo "No APK files found"
        ls -la app/build/outputs/ || echo "No outputs directory"
        ls -la app/build/outputs/apk/ || echo "No apk directory"
        ls -la app/build/outputs/apk/debug/ || echo "No debug directory"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/*.apk
